android {
    namespace 'com.example.printer'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.printer"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    // إضافة توافق جافا مع الإصدار 17
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // إضافة توافق كوتلن مع الإصدار 17
    kotlinOptions {
        jvmTarget = '17'
    }
}